### ISSUE TITLE
起動できない

### ISSUE THREAD

**Issue by rohme** [rohme/EnjoyFishing#1]
元の内容は#9へ移動

**Comment by irohanihohe10** [comment]
2015-09-19 Ver1.1.6を起動してキャラクターを選ぶところまではいくのですが起動できません。
ダウンロードして、管理者としてこのプログラムを実行にチェックしました。
2015-08-22 Ver1.1.5までは普通に使えていましたが、なにか必要なものがあるのでしょうか？

**Comment by rohme** [comment]
起動できないとはどのような状態になりますか？（いつまで待っても画面が表示されないとか、プロセスが残ったままになるとか）
それと、起動パラメータに「/d /ll:0」を追加して起動すると、EXEと同じ所にログファイルが生成されますので、自分のキャラクター名を修正してアップしてもらうと原因が特定できるかもしれません。
ちなみに、今回はチャット周りを修正しただけで、1.1.5と大きく環境は変わっていないはずです。

**Comment by irohanihohe10** [comment]
返信ありがとうございます！
症状はダブルクリックをして、POLの選択ウィンドウからキャラクター名を選ぶと
いつもの画面が表示されず、そのまま何も起こらない状態になってしまいます。
単窓で起動しても画面が表示されないままの状態になってしまいます。

タスクマネージャーを起動してみましたがプロセス？は残っていませんでした。
「/d /ll:0」を付け加えてコマンドプロントから起動してみましたがログは生成されませんでした。

**Comment by rohme** [comment]
ログが生成されていないとなると、Polプロセスが取れていないのかもしれません。
新しいディレクトリに1.1.6を解凍して、以下からダウンロードしたファイルを上書きして実行してみてください。
http://www1.axfc.net/u/3536520/ff11
何かしらメッセージが表示されると思いますので、それを教えてくれませんか？

**Comment by irohanihohe10** [comment]
起動中のPolプロセス数：1
プロセス1：6352 Hogehoge(キャラ名)
というメッセージが出たのですが、OKを押すと起動エラーみたいなアラートが出ました。
その後、繰り返すとまた無反応という状況です。

少し前からEnjoyFishngを使わせていただいているのですが最初は使い方がわかっていなくて
本体を複製して多重起動していました。そのときにも同じようなエラーが出たことがありました。
自分PC固有の問題のようですし、もしかして起動環境が破損しているような感じなのでしょうか？
これからもう一度、必要な起動環境のアプリを再インストールしてみたいと思います。
わざわざ深夜まで付き合っていただきありがとうございます＞＜

**Comment by irohanihohe10** [comment]
いろいろ試してみたのですが、うまくいかなかったのでOSの再インストールからやり直すことにしました！
手厚いサポートをありがとうございましたm(_ _)m
ありがたく使わせていただきます。これからもよろしくお願いします。

**Comment by irohanihohe10** [comment]
何度もすみません。PCをフォーマットしてOSを入れ直したのですがうまくいきませんでした。

ダウンロードしたファイルを解凍して、管理者としてこのプログラムを実行をチェック
ダブルクリックで起動すると
起動中のPolプロセス数：1
プロセス1：6352 Hogehoge(キャラ名)
みたいなウィンドウが出てきて、OKを押すとなにも起きずという感じです。
セキュリティソフトはNortonインターネットセキュリティですが切っても変わらずでした。
IMはATOKPassportです。

インストールしたもの
Microsoft .NET Framework 4.5
Visual Studio 2013 の Visual C++ 再頒布可能パッケージ(X86版)

備考：試しにEasyFarmを起動してみたら普通に使えました。
またお力を貸していただけると幸いです＞＜どうかよろしくお願いします。

**Comment by rohme** [comment]
ああ、そういえばシフトキーを押しっぱなしで起動すると、FFACEのテスト画面が表示されるのですが、それは表示されていますか？

**Comment by irohanihohe10** [comment]
こんにちは！無事に起動することができました。
左と右でシフトキー試しましたがテスト画面は表示されませんでした。
しかしFFACE.dllを本家？からダウンロードしてきて、置き換えたら無事に起動できました！
（OSを入れ替える前にも、最新のFFACEやEliteAPIの.dllファイルを置き換えてみたのですが
そのときは起動できませんでした。）
親切なサポートをありがとうございましたm(_ _)m

**Comment by rohme** [comment]
うへ、結局なんだったんだろう＾＾；
リリースしたものに同胞したファイルが古かったのか見てみたけど、問題なかったですし・・・
とにかく動いてよかったです！

あ、あと質問は大歓迎なのですが、新規の問題は画面右上にある「New issue」という緑色のボタンから投稿してください。
話題が混ざるとわけ分からなくなるので・・・

**Comment by irohanihohe10** [comment]
いろいろとお世話になりました。
New issueの件、了解ですｗ
不慣れでご迷惑おかけしました＞＜
