### ISSUE TITLE
EnjoyFishing1.1.6になってから起動しなくなりました。

### ISSUE THREAD

**Issue by kool924jp** [rohme/EnjoyFishing#10]
タイトルの通り、EnjoyFishing1.1.6になってから、起動しなくなくなりました。
WIN10 64BIT
WIN7 32BIT
の環境で試したのですが、起動すらしなくなりました。
すみませんが、確認をおねがいいたします。

**Comment by kool924jp** [comment]
大変失礼しました。
別の投稿を拝見して、FFACE.dllの最新を入れたら起動するようになりました。
とても重宝しておりますので、今後共、どうぞよろしくお願い致します。

**Comment by rohme** [comment]
1.1.6に同胞しているFFACEは、もう古いバージョンみたいで動かないみたいですね。
最新のFFACEをダウンロードして使用してください。

**Comment by kool924jp** [comment]
早速のご返信有り難うございます。
これからもどうぞよろしくお願い致します。
