### ISSUE TITLE
1.2.0におけるFFからのEnjoyFishingの制御とEliteAPI

### ISSUE THREAD

**Issue by SRJRT** [rohme/EnjoyFishing#16]
1.2.0への更新お疲れ様です。そしてありがとうございます。
早速ですが、FFACE版使用していた/echoでの操作が出来なくなっているようですが、これは仕様でしょうか？

**Comment by rohme** [comment]
もしかして、チャットにタイムスタンプを表示する設定にしていますか？
今やってみたら、その場合は動かないみたいなので、修正したいと思います。

**Comment by SRJRT** [comment]
対応ありがとうございます。
Windower4のTimestampは起動時のAddonの読み込みとハラキリにも影響が有りましたので、
プログラムを起動する前に手動でOFFにしていました。
FFXI公式のタイムスタンプも使用していません。
1.1.7ではこの事前の準備だけで/echoでの操作が出来ていたので質問させて頂きました。
修正されるまで少し環境を変えて色々試して見たいと思います。

**Comment by rohme** [comment]
アドオンとプラグインをすべて切ってどうなるか知りたいですね。
ちなみに、私のところで試してみた場合、以下の通りになりました。
タイムスタンプなし→OK
公式タイムスタンプ[HH:MM]→NG
公式タイムスタンプ[HH:MM:SS]→OK
TimeStampアドオン→OK
公式タイムスタンプとTimeStampアドオンの併用→NG

今までタイムスタンプの事は一切考慮していなかたので、対応してみたいと思います。

**Comment by irohanihohe10** [comment]
開発の継続ありがとうございます。
イシューを作るほどでもないと思ったのでイシュー違い失礼します。
2015-03-28 Ver1.2.0は2016-03-28 Ver1.2.0だと思います。

**Comment by rohme** [comment]
おおぅ
直しときました！

**Comment by SRJRT** [comment]
修正ありがとうございます。
1.2.0でAddonを全て切った状態でも上手く動作しませんでした。
せっかくなので1.2.1へ移行してみたのですが、各種タイムスタンプ有り無しとも関係なく受け付けないようでした。
あれこれ組み合わせを試してみたところ、どうやら大文字小文字の区別がされているようで
（当方はManualの原文ままコピペでマクロに仕込んでいた為）動かなかったようです。
操作に関してはおかげさまで解決出来ました。
タイムスタンプを切らずに起動出来るバージョンすごく良いです！ありがとうございます！

しかし新たな問題を2つほど発見しましたのでご報告です。
以下は1.2.0,1.2.1にてtimestamp有無問わず確認出来た問題で、PC2台とも同じことが起こります。
その前に私の環境を書いたほうが良さそうですね。
OS:Windows7proとHomeの2台Addonも同じものです。
Addon:AutoInvite AutoJoin Cancel ConsoleBG Distance enternity findAll Itemizer Logger
PetTP Scoreboard Silence SpeedCheker TParty zonetimer
FFXIのウィンドウ分割は有無混在

1．何の前触れもなくプログラムがフリーズしたように釣りの動作、格闘をしなくなる
雑魚、モノ、何もかからず、ターゲット等どの状態からでも唐突に発生します。
 一度停止ボタンを押して再度開始しても動作は正常に戻らない。
再起動すると通常に動作する。
結構な頻度で発生しますが、しない時は直ったかのように発生しなかったりでよくわかりません。

2．EnjoyFishing「釣り」の「情報」タブに出てくるCatch情報が以下の様に表示される時がある。

ググリューサウルスを手にいれた！(自キャラ名)はググリューサウルス

Historyファイルのログがこのようになっています。
[INFO ]魚の追加 竿=恵比寿釣竿 魚=ググリューサウルスを手にいれた！(自キャラ名)はググリューサウルス 魚タイプ=LargeFish ID=100-1160-007-430 エリア=外洋航路：マウラ行き エサ=肉ダンゴ - EnjoyFishing.FishDB.AddFish() 
 [INFO ] 釣果：ググリューサウルスを手にいれた！(自キャラ名)はググリューサウルスL - EnjoyFishing.FishingTool.setMessage() 

以上の2つです。

2は見た目だけなので、Historyのログを手直しでなんとかなりそうです。
1はここ1年くらいのFFのログがややこしいから停止してしまうのですかね。
色々試してみたのですが、必ず止まるわけではないのでAddonが原因なのかもよくわかりません。

**Comment by rohme** [comment]
まず、FFからの釣り開始コマンドですが、パラメータ（start/stop）が小文字じゃないと動作しないようになっていました！ごめんなさい<(_ _)>

そして１，２の件ですが、現象を見る限りEliteAPIから同じチャットを複数回受け取るときがあるのかもしれませんね。
対策を施したバージョンを http://www1.axfc.net/u/3643905/ff11 にアップしてみましたので、これでどうなるかちょっと試してもらえませんか？（オリジナルのVer1.2.1に上書きしてください。）
これで不具合が解消すればいいのですが、もし同様の現象が発生した場合、ログファイルを確認してみてほしいのです。
ログファイルにチャットバッファに追加しているチャット内容が表示されます（ ”チャットバッファに追加：ほにゃらら”と記録されています）ので、まったく関係ない行がくっついていたり、おかしな文字列が入っているかを確認してみてほしいのです。
よくわからない場合は、ここにアップしてくださいな。

**Comment by rohme** [comment]
Ver1.2.2で修正
