### ISSUE TITLE
鞄がいっぱいなので停止

### ISSUE THREAD

**Issue by daisuke14** [rohme/EnjoyFishing#17]
いつもお疲れ様です。
Ver up後、鞄がいっぱいなので停止となり開始できなくなったのですが、
何か私の設定がまちがっているのでしょうか？

**Comment by rohme** [comment]
FFのクライアントがバージョンアップされた場合、EliteAPI.dllとEliteMMO.API.dllをバージョンアップに対応したものへと更新する必要があります。
[README.mdの#動かない場合](https://github.com/rohme/EnjoyFishing/blob/master/README.md#動かない場合)に記載されているURLより入手してください。

**Comment by daisuke14** [comment]
初歩的なミスをしておりました。
ありがとうございます、助かりました。
