### ISSUE TITLE
鞄が一杯で釣りが出来ないといわれてしまう。

### ISSUE THREAD

**Issue by neoalchemist13** [rohme/EnjoyFishing#19]
鞄他全ておかしな数字に化けており鞄が一杯で釣りができないとなってしまうのを修正してください。

**Comment by rohme** [comment]
ご自身でクローズされていますが、勘違い？

**Comment by rohme** [comment]
確認してみましたが、鞄の数は正常に取得できているようです。
EliteAPIを更新していないかも？
反応なければこのままクローズとしちゃいます。
